#!/bin/sh

. /lib/functions.sh

if ! uci show luci.themes.LifeLine 2>/dev/null| grep LifeLine >/dev/null
then 

uci set luci.themes.LifeLine='/luci-static/lifeline'
uci set luci.main.mediaurlbase='/luci-static/lifeline'
uci commit 

fi

exit 0
