#!/bin/sh

. /usr/share/lifeline/common.sh

log_init lifeline

log debug "online ${INTERFACE} ${DEVICE} ${GLOBAL}"

if [ "${INTERFACE}" = "wan" ]
then
        log debug "switching backup off"
        uci set wireless.llback.disabled=1
        /etc/init.d/network reload
fi

