#!/bin/sh

. /usr/share/lifeline/common.sh

log_init lifeline

log debug "offline ${INTERFACE} ${DEVICE} ${GLOBAL}"

if [ "${INTERFACE}" = "wan" ]
then
        log debug "switching backup on"
        uci set wireless.llback.disabled=0
        /etc/init.d/network reload
fi

