#!/bin/ash

. /usr/share/lifeline/common.sh

BACKUP_ACTIVE=0
FAIL_COUNT=0
PRIMARY_INTERFACE=`uci get lifeline.global.primary_interface`
BACKUP_INTERFACE=`uci get lifeline.global.backup_interface`
PRIMARY_PING=`uci get lifeline.global.primary_ping`

log_init "lifeline"

log debug "Lifeline process starting"
log debug "Primary interface is $PRIMARY_INTERFACE - ping $PRIMARY_PING"
log debug "Backup interface is $BACKUP_INTERFACE"

while : 
do
	#log debug "Loop"

	if ! ping -4 -q -c 1 -W 2 -I $PRIMARY_INTERFACE $PRIMARY_PING >/dev/null 
	then
		log debug "PING failed - fail count = ${FAIL_COUNT}"
		FAIL_COUNT=$((FAIL_COUNT+1))
	else
		FAIL_COUNT=0
	fi

	if [ $FAIL_COUNT -gt 1 ]
	then
		if [ $BACKUP_ACTIVE -eq 0 ]
		then
			log debug "Activating backup"
			uci set wireless.${BACKUP_INTERFACE}.disabled=0
			/etc/init.d/network reload
			BACKUP_ACTIVE=1
		fi
	else
		if [ $BACKUP_ACTIVE -eq 1 ]
		then
			log debug "Deactivating backup"
			uci set wireless.${BACKUP_INTERFACE}.disabled=1
			/etc/init.d/network reload
			BACKUP_ACTIVE=0
		fi
	fi

	sleep 5
done

