#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
NAME=lifeline

start_service() {

	if [ -x "/usr/sbin/lifeline" ]; then
		procd_open_instance lifeline
		procd_set_param command /usr/sbin/lifeline
		procd_set_param respawn 3600 1 0
		[ -x /sbin/ujail -a -e /etc/capabilities/lifeline.json ] && {
			procd_add_jail lifeline
			procd_set_param capabilities /etc/capabilities/lifeline.json
		}
		procd_close_instance
	fi

}

