#!/bin/ash

. /lib/functions.sh

if [ "`uci get wireless.llback 2>/dev/null`" != "wifi-iface" ]
then 
	uci set wireless.llback=wifi-iface
	uci set wireless.llback.device='radio0'
	uci set wireless.llback.mode='sta'
	uci set wireless.llback.ssid='llback'
	uci set wireless.llback.encryption='psk2'
	uci set wireless.llback.key='SuperSecret'
	uci set wireless.llback.network='llback'
        uci commit 
        /etc/init.d/network reload
fi

exit 0 

