#!/bin/ash

. /lib/functions.sh

if ! uci show pingcheck | grep "name=" | grep llback >/dev/null
then
        uci add pingcheck interface
        uci set pingcheck.@interface[-1].name=llback

        uci commit
        reload_config
fi

exit 0 

