#!/bin/sh

. /lib/functions.sh

uci add firewall rule
uci set firewall.@rule[-1].name='luci'
uci set firewall.@rule[-1].src='wan'
uci set firewall.@rule[-1].target='ACCEPT'
uci set firewall.@rule[-1].proto='tcp'
uci set firewall.@rule[-1].dest_port='443'
uci commit 

/etc/init.d/firewall restart

exit 0
